config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end


  resources :attachments, only: :destroy

  get :search, to: "search#index"

  resources :questions do
    resources :answers do
      member do
        patch :best
      end
    end
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :questions, concerns: %i[votable commentable]
  resources :answers, concerns: %i[votable commentable]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many  :subscriptions, dependent: :destroy
  has_many  :subscribe_users, through: :subscriptions, source: :user, class_name: "User"

  has_many_attached :files

  scope :daily, -> { where(created_at: 1.day.ago..Time.current) }

  validates :title, :body, presence: true

  after_create :subscribe_user

  private

  def subscribe_user
    self.user.subscribe_questions << self
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController <  Api::V1::BaseController
  before_action :find_question, only: [:update, :destroy, :show]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    if @question.save
      render json: @question
    else
      head  422
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      head  422
    end
  end

  def destroy
    @question.destroy
  end

  private
  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: [:id, :name, :url, :_destroy])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.build
    @question = Question.with_attached_files.find(params[:id])
    gon.question_id = @question.id
    gon.question_author_id = @question.user_id
  end

  def new
    question.links.build
    question.comments.build
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created'
    else
      render :new
    end
  end

  def update
    question.update(question_params)
  end

  def destroy
    authorize! :destroy, question
    question.destroy
    redirect_to root_path
  end

  helper_method :question

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
     'questions',
     ApplicationController.render(
       partial: 'questions/question',
       locals: { question: @question }
     )
   )
  end

  def question
    @question ||= params[:id] ? Question.find(params[:id]) : Question.new
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                      files: [], links_attributes: [:id, :name, :url, :_destroy])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper

  def for_author_question_add_link_delete(question)
    if can?(:delete, question)
      link_to 'Delete question', question_path(question), method: :delete
    end
  end

  def subscribe_link(question)
    subscription = current_user.subscriptions.find_by(question: question)
    if subscription
       link_to 'unsubscribe', question_subscription_path(subscription, question_id: question.id), method: :delete, class: "subscription", remote: true
    else
       link_to 'subscribe', question_subscriptions_path(question_id: question.id), method: :post, class: "subscription", remote: true
    end
  end
end

app/views/questions/_question.html.slim
= content_tag :div, class: 'question-summary', data: { question_id: question.id }
  =link_to question_path(question)
    = question.title

app/views/questions/index.html.slim
.search-form
  = form_with url: search_path, method: :get, local: true do |f|
    = f.label 'query', "Search for:"
    = f.text_field 'query'
    = f.select('model', options_for_select(%w[question answer comment user all]))
    = f.submit "Search"

- if can?(:create, Question)
  p = link_to 'Ask question', new_question_path
.questions
  = render @questions

app/views/questions/new.html.slim
.question-errors
  = render 'shared/errors', resource: question

.col-6 class="alert alert-secondary"
  = form_with model: question, url: questions_path, local: true do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
      = f.label :body
      = f.text_area :body, class: 'form-control'
      = f.label :files
      = f.file_field :files, multiple: true

      .links
        = f.fields_for :links do |link|
          = render 'link_fields', :f => link
        .link-add
          = link_to_add_association 'add link', f, :links

      .comments
        = f.fields_for :comments do |comment|
          = comment.label :body, 'Comment'
          = comment.text_field :body, class: 'form-control'

      = f.submit 'Ask', class: 'btn btn-secondary btn-sm btn-block'

  = button_to 'Back', root_path, class: 'btn btn-secondary btn-sm btn-block', method: :get

app/views/questions/show.html.slim
.question-errors
.question
  .row
    -if user_signed_in?
      = render 'shared/vote', resource: @question

    .col-6.alert.alert-secondary
      -if user_signed_in?
        p =subscribe_link(@question)
      - cache @question do
        h2 = @question.title
        p = @question.body
        - if @question.files.attached?
          = render @question.files
        = render 'shared/link', resourse: @question

      - cache ['comments-question', question] do
        p Comments:
        div class="comments-question"
          = render question.comments

      - if can?(:create, Comment)
        .errors-comment-question-form
        div class="comment-question-form"
          = render 'comments/form', resource: Comment.new, url: question_comments_path(@question)

      = form_with model: question, class: 'hidden', html: { id: "edit-question" } do |f|
        .form-group
          = f.label :title, 'Your question title'
          = f.text_field :title, class: 'form-control'
          = f.label :body, 'Your question body'
          = f.text_area :body, class: 'form-control'
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true
          = render 'shared/form_link', :f => f

          = f.submit 'Save', class: 'btn btn-secondary btn-sm btn-block'

    - if can?(:update, question)
      .col-1.alert.alert-secondary
        p= link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
        p= link_to 'Delete', question_path(question), method: :delete

.answers
  = render @question.answers.with_attached_files

.answers_form
  -if can?(:create, Answer)
    = render 'answers/form'

= link_to 'Back', root_path

app/views/questions/subscribe.js.erb
$('.question').html('<%= j render 'shared/question', resource: @question %>')

app/views/questions/update.js.erb
$('.question-errors').html('<%= j render 'shared/errors', resource: @question %>')
<% if @question.errors.blank? %>
  $('.question').html('<%= j render 'shared/question', resource: @question %>')
<% end %>