config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end


  resources :attachments, only: :destroy

  get :search, to: "search#index"

  resources :questions do
    resources :answers do
      member do
        patch :best
      end
    end
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :questions, concerns: %i[votable commentable]
  resources :answers, concerns: %i[votable commentable]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, touch: true

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  after_action :publish_comment, only: [:create]

  authorize_resource

  def create
    @comment = commentable.comments.build(comment_params.merge(user: current_user))
    @comment.save
  end

  private

  def commentable
    if params[:question_id]
      Question.find(params[:question_id])
    else
      Answer.find(params[:answer_id])
    end
  end

  def question_id
    commentable.respond_to?(:question_id) ? commentable.question.id : commentable.id
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def publish_comment
    return if @comment.errors.any?
    ActionCable.server.broadcast(
      "comments-for-question-#{question_id}",
      comment: @comment
    )
  end

end

app/views/comments/_comment.html.slim
- cache comment do
  p= comment.body

app/views/comments/_form.html.slim
= form_for resource, url: url, remote: true do |f|
  = f.text_field :body, class: 'form-control'

  = f.submit 'Add comment', class: 'btn btn-sm btn-secondary'

app/views/comments/create.js.erb
<% if @comment.commentable_type == 'Answer'%>
  $('.errors-comment-answer-form-'+<%= @comment.commentable_id %>).html('<%= j render 'shared/errors', resource: @comment %>')
  <% if @comment.persisted? %>
    $(".comments-answer-"+<%= @comment.commentable_id %>).before('<%= j render 'comments/comment', comment: @comment %>')
    $(".comment-answer-form-"+<%= @comment.commentable_id %>).html('<%= j render 'comments/form', resource: Comment.new, url: answer_comments_path(@comment.commentable_id) %>')
  <% end %>
<% end %>

<% if @comment.commentable_type == 'Question'%>
  $('.errors-comment-question-form').html('<%= j render 'shared/errors', resource: @comment %>')
  <% if @comment.persisted? %>
    $(".comments-question").before('<%= j render 'comments/comment', comment: @comment %>')
    $(".comment-question-form").html('<%= j render 'comments/form', resource: Comment.new, url: question_comments_path(@comment.commentable_id) %>')
  <% end %>
<% end %>